using SQL_EntityFramework.Classes;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;
using System.Windows;
using System.Windows.Controls;
using System.Windows.Data;
using System.Windows.Documents;
using System.Windows.Input;
using System.Windows.Media;
using System.Windows.Media.Imaging;
using System.Windows.Shapes;

namespace SQL_EntityFramework.WPF
{
    public partial class AddEmployee : Window
    {
        int projectID= -1;
        int employeeID= -1;
        public AddEmployee(int projectID)
        {
            InitializeComponent();
            this.projectID = projectID;
            updateGrid();
        }

        private void updateGrid()
        {
            gridAddEmployee.ItemsSource = Logic.fillEmployeesToAdding(projectID);
        }

        private void gridAddEmployee_AutoGeneratedColumns(object sender, EventArgs e)
        {
            gridAddEmployee.Columns[0].Visibility = Visibility.Hidden;
            gridAddEmployee.Columns[1].Header = "Имя";
            gridAddEmployee.Columns[2].Header = "Фамилия";
            gridAddEmployee.Columns[3].Header = "Отчество";
            gridAddEmployee.Columns[4].Header = "Email";
            gridAddEmployee.Columns[5].Visibility = Visibility.Hidden;
        }

        private void buttonCancel_Click(object sender, RoutedEventArgs e)
        {
            this.Close();
        }

        private void buttonAdd_Click(object sender, RoutedEventArgs e)
        {
            if(employeeID != -1)
            {
                Logic.createProjectEmployee(projectID, employeeID);
                MessageBox.Show("Сотрудник добавлен в проект", "Уведомление");
                updateGrid();
                
            }
            else
            {
                MessageBox.Show("Нужно выбрать элемент", "Ошибка");
            }

        }

        private void gridAddEmployee_SelectionChanged(object sender, SelectionChangedEventArgs e)
        {
            try
            {
                Employee employee = (Employee)gridAddEmployee.SelectedItem;
                employeeID = employee.Employee_ID;
            }
            catch
            {
                employeeID = -1;
            }
        }
    }
}
